server.port=${SERVER_PORT:8090}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/api/v1}
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jackson.deserialization.fail-on-unknown-properties=true
jwt.expiration=${JWT_EXPIRATION:900000}
jwt.refresh.expiration=${JWT_REFRESH_EXPIRATION:3000000}
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER:wine-service-app}
jwt.audience=${JWT_AUDIENCE:wine-service-api}
management.server.port=${MANAGEMENT_SERVER_PORT:9090}
management.endpoints.web.exposure.include=health,prometheus
management.metrics.tags.application=wine-app
management.endpoint.health.probes.enabled=true
management.endpoint.health.show-details=never
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.jpa.properties.hibernate.format_sql=true
spring.liquibase.contexts=${LIQUIBASE_CONTEXTS:}
logging.level.org.hibernate.SQL=DEBUG
management.endpoint.health.group.readiness.include=readinessState,db
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend.url=${FRONTEND_URL}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
cloud.r2.access-key=${R2_ACCESS_KEY}
cloud.r2.secret-key=${R2_SECRET_KEY}
cloud.r2.endpoint=${R2_ENDPOINT}
cloud.r2.bucket-name=${R2_BUCKET_NAME}
cloud.r2.public-url=${R2_PUBLIC_URL}
stripe.api-key=${STRIPE_SECRET_KEY}
